"use client";

import { useState, useEffect } from "react";
import { Loader2, Image as ImageIcon, Check, Upload as UploadIcon, Award } from "lucide-react";
import { toast } from "sonner";
import { TransactionButton, useActiveAccount } from "thirdweb/react";
import { getContract } from "thirdweb";
import { mintTo } from "thirdweb/extensions/erc721";
import { upload } from "thirdweb/storage";
import { client, chain } from "@/lib/thirdweb";

// User's specific ERC-721 contract
const CERTIFICATE_CONTRACT_ADDRESS = "0x11201AC249186142f9acC61f79510eE0defb31F0";

interface Attendee {
  wallet_address: string;
  full_name: string;
  email: string;
  ticket_bought_at: string;
  is_certificate_sent: boolean;
}

interface CompletedEvent {
  id: string;
  title: string;
}

export default function CertificatesPage() {
  const account = useActiveAccount();
  const contract = getContract({ client, chain, address: CERTIFICATE_CONTRACT_ADDRESS });

  const [completedEvents, setCompletedEvents] = useState<CompletedEvent[]>([]);
  const [eventId, setEventId] = useState<string>("");

  const [attendees, setAttendees] = useState<Attendee[]>([]);
  const [isLoading, setIsLoading] = useState(false);

  // Form states
  const [selectedAttendeeWallet, setSelectedAttendeeWallet] = useState<string>("");
  const [certFile, setCertFile] = useState<File | null>(null);
  const [isUploading, setIsUploading] = useState(false);

  // 1. Fetch completed events on mount
  useEffect(() => {
    const fetchCompletedEvents = async () => {
      try {
        const res = await fetch('/api/events/completed');
        const data = await res.json();
        if (res.ok) {
          setCompletedEvents(data.events);
        }
      } catch (err) {
        console.error("Failed to fetch completed events:", err);
      }
    };
    fetchCompletedEvents();
  }, []);

  // 1b. Pick up a pending certificate generated by the Design page
  useEffect(() => {
    const pendingDataUrl = sessionStorage.getItem("pendingCertDataUrl");
    const pendingName    = sessionStorage.getItem("pendingCertName");
    const pendingWallet  = sessionStorage.getItem("pendingCertWallet");

    if (pendingDataUrl && pendingName) {
      // Convert dataURL → File
      fetch(pendingDataUrl)
        .then(r => r.blob())
        .then(blob => {
          const file = new File([blob], pendingName, { type: "image/png" });
          setCertFile(file);
          toast.success("Certificate design imported!", {
            description: "Image loaded from the Design page.",
          });
        });

      if (pendingWallet) setSelectedAttendeeWallet(pendingWallet);

      // Clear so it doesn't persist on refresh
      sessionStorage.removeItem("pendingCertDataUrl");
      sessionStorage.removeItem("pendingCertName");
      sessionStorage.removeItem("pendingCertWallet");
    }
  }, []);

  // 2. Automatically fetch attendees when event changes
  useEffect(() => {
    // Only reset the attendee selector, NOT the file — the image should persist
    setSelectedAttendeeWallet("");

    if (!eventId) {
      setAttendees([]);
      return;
    }

    const fetchAttendees = async () => {
      setIsLoading(true);
      try {
        const res = await fetch(`/api/events/${eventId}/attendees`);
        const data = await res.json();
        if (res.ok) {
          setAttendees(data.attendees);
          if (data.attendees.length > 0) {
            toast.success(`Loaded ${data.attendees.length} attendees.`);
          }
        } else {
          toast.error("Failed to fetch attendees", { description: data.error });
        }
      } catch (err) {
        toast.error("Error fetching attendees");
      } finally {
        setIsLoading(false);
      }
    };

    fetchAttendees();
  }, [eventId]);

  const handleFileChange = (e: React.ChangeEvent<HTMLInputElement>) => {
    setCertFile(e.target.files?.[0] || null);
  };

  const getEventTitle = () => {
    const evt = completedEvents.find(e => e.id === eventId);
    return evt ? evt.title.split(' (')[0] : "Event";
  };

  const selectedAttendee = attendees.find(a => a.wallet_address === selectedAttendeeWallet);

  return (
    <div className="max-w-3xl mx-auto space-y-6">
      <div className="flex flex-col lg:flex-row items-start lg:items-center justify-between mb-8 gap-4">
        <div>
          <h1 className="text-3xl font-bold text-white bg-gradient-to-r from-purple-400 to-cyan-400 bg-clip-text text-transparent">
            Mint Certificate (ERC-721)
          </h1>
          <p className="text-gray-400 mt-2">Issue a unique certificate NFT to an event attendee.</p>
        </div>
      </div>

      <div className="glass border border-purple-500/30 rounded-xl p-6 sm:p-8 space-y-8 relative overflow-hidden">
        {/* subtle background glow */}
        <div className="absolute top-0 right-0 p-32 bg-purple-500/10 blur-[100px] pointer-events-none rounded-full" />
        
        <div className="flex items-center gap-3 border-b border-purple-500/20 pb-4">
          <div className="p-2 bg-purple-500/20 rounded-lg border border-purple-500/30">
            <Award className="w-5 h-5 text-purple-400" />
          </div>
          <h2 className="text-xl font-semibold text-white">Certificate Details</h2>
        </div>

        <div className="space-y-6 relative z-10">
          
          {/* 1. Select Event */}
          <div className="space-y-2">
            <label className="block text-sm font-medium text-gray-300">
              1. Select Completed Event
            </label>
            <div className="flex items-center gap-3">
              <select
                value={eventId}
                onChange={(e) => setEventId(e.target.value)}
                className="flex-1 bg-black/50 border border-purple-500/30 rounded-xl px-4 py-3 text-white focus:outline-none focus:border-purple-500/80 focus:ring-1 focus:ring-purple-500/50 appearance-none transition-all"
              >
                <option value="">-- Choose an Event --</option>
                {completedEvents.map((evt) => (
                  <option key={evt.id} value={evt.id}>
                    {evt.title}
                  </option>
                ))}
              </select>
              {isLoading && (
                <Loader2 className="w-5 h-5 animate-spin text-purple-400 flex-shrink-0" />
              )}
            </div>
          </div>

          {/* 2. Select Attendee */}
          <div className="space-y-2">
            <label className="block text-sm font-medium text-gray-300">
              2. Select Attendee
            </label>
            <select
              value={selectedAttendeeWallet}
              onChange={(e) => setSelectedAttendeeWallet(e.target.value)}
              disabled={!eventId || attendees.length === 0}
              className="w-full bg-black/50 border border-purple-500/30 rounded-xl px-4 py-3 text-white disabled:opacity-50 disabled:cursor-not-allowed focus:outline-none focus:border-purple-500/80 focus:ring-1 focus:ring-purple-500/50 appearance-none transition-all"
            >
              <option value="">
                {eventId && attendees.length === 0 && !isLoading
                  ? "No attendees found for this event"
                  : "-- Choose an Attendee --"}
              </option>
              {attendees.map((a) => (
                <option 
                  key={a.wallet_address} 
                  value={a.wallet_address}
                  disabled={a.is_certificate_sent}
                >
                  {a.full_name} ({a.wallet_address.substring(0, 6)}...{a.wallet_address.substring(a.wallet_address.length - 4)})
                  {a.is_certificate_sent ? " — Already Minted" : ""}
                </option>
              ))}
            </select>
            {eventId && attendees.length > 0 && (
               <p className="text-xs text-gray-500 mt-1 pl-1">
                 {attendees.filter(a => a.is_certificate_sent).length} of {attendees.length} certificates already minted.
               </p>
            )}
          </div>

          {/* 3. Upload File */}
          <div className="space-y-2">
            <label className="text-sm font-medium text-gray-300 flex items-center justify-between">
              <span>3. Certificate Image</span>
              {certFile && (
                <button
                  type="button"
                  onClick={() => setCertFile(null)}
                  className="text-xs text-red-400 hover:text-red-300 transition-colors px-2 py-0.5 rounded border border-red-500/20 hover:border-red-500/40"
                >
                  Clear
                </button>
              )}
            </label>

            {certFile ? (
              /* ── File already loaded: show preview card ── */
              <div className="w-full border-2 border-green-500/40 bg-green-500/5 rounded-xl overflow-hidden">
                {/* Thumbnail */}
                <div className="relative w-full h-36 bg-black/30">
                  {/* eslint-disable-next-line @next/next/no-img-element */}
                  <img
                    src={URL.createObjectURL(certFile)}
                    alt="Certificate preview"
                    className="w-full h-full object-contain"
                  />
                </div>
                {/* File info */}
                <label className="flex items-center justify-between px-4 py-3 cursor-pointer hover:bg-green-500/10 transition-colors group">
                  <div className="flex items-center gap-2">
                    <Check className="w-4 h-4 text-green-400 flex-shrink-0" />
                    <div>
                      <p className="text-green-400 font-semibold text-sm line-clamp-1">{certFile.name}</p>
                      <p className="text-green-500/50 text-xs">{(certFile.size / 1024).toFixed(1)} KB · Click to replace</p>
                    </div>
                  </div>
                  <UploadIcon className="w-4 h-4 text-green-400/50 group-hover:text-green-400 transition-colors" />
                  <input type="file" accept="image/*" className="hidden" onChange={handleFileChange} />
                </label>
              </div>
            ) : (
              /* ── No file yet: upload prompt ── */
              <label className={`block w-full border-2 border-dashed rounded-xl p-8 transition-all text-center
                ${!selectedAttendeeWallet
                  ? 'border-gray-700 bg-gray-900/50 opacity-50 pointer-events-none cursor-not-allowed'
                  : 'border-purple-500/30 hover:border-purple-500/50 bg-black/20 hover:bg-purple-500/5 cursor-pointer'}
              `}>
                <input type="file" accept="image/*" className="hidden" onChange={handleFileChange} disabled={!selectedAttendeeWallet} />
                <div className="flex flex-col items-center gap-3">
                  <div className="w-12 h-12 rounded-full flex items-center justify-center bg-purple-500/20 text-purple-400">
                    <ImageIcon className="w-6 h-6" />
                  </div>
                  <div>
                    <p className={!selectedAttendeeWallet ? "text-gray-500 font-medium" : "text-gray-300 font-medium"}>
                      {!selectedAttendeeWallet ? "Select an attendee first" : "Click or drag to select image"}
                    </p>
                    <p className="text-gray-500 text-xs mt-1">PNG, JPG, GIF — or use the Design Certificate tool</p>
                  </div>
                </div>
              </label>
            )}
          </div>

        </div>

        {/* Action Button */}
        <div className="pt-4 border-t border-purple-500/20">
          {!account ? (
            <button disabled className="w-full h-14 bg-gray-800 text-gray-500 border border-gray-700 font-bold rounded-xl text-lg transition-all">
              Connect Wallet
            </button>
          ) : (
            <TransactionButton
              disabled={!selectedAttendeeWallet || !certFile}
              transaction={async () => {
                if (!selectedAttendeeWallet) throw new Error("Please select an attendee.");
                if (!certFile) throw new Error("Please upload a Certificate image.");
                if (!selectedAttendee) throw new Error("Invalid attendee selected.");

                setIsUploading(true);
                let imageUri = "";
                try {
                  const uris = await upload({ client, files: [certFile] });
                  imageUri = Array.isArray(uris) ? uris[0] : uris;
                } catch (err) {
                  setIsUploading(false);
                  throw new Error("Failed to upload image to IPFS");
                }
                setIsUploading(false);

                const metadata = {
                  name: `${selectedAttendee.full_name}'s Certificate`,
                  description: `Official Certificate of Attendance for ${getEventTitle()}`,
                  image: imageUri,
                  attributes: [
                      { trait_type: "Type", value: "Certificate" },
                      { trait_type: "Attendee", value: selectedAttendee.full_name }
                  ]
                };

                console.log("=== MINT TRANSACTION PRE-FLIGHT CHEX ===");
                console.log("Admin (Sender):", account?.address);
                console.log("Attendee (Receiver):", selectedAttendeeWallet);
                console.log("Certificate NFT Metadata:", metadata);

                if (!account?.address || !selectedAttendeeWallet || !imageUri) {
                  const errMsg = "Missing vital minting data (sender, receiver, or image uri). Transaction prevented.";
                  console.error(errMsg);
                  alert(errMsg);
                  throw new Error("Missing minting data.");
                }

                return mintTo({
                  contract,
                  to: selectedAttendeeWallet,
                  nft: metadata
                });
              }}
              onTransactionConfirmed={async (receipt) => {
                try {
                  // 1. Mark certificate as minted in the database
                  await fetch('/api/certificates', {
                    method: "POST",
                    headers: { "Content-Type": "application/json" },
                    body: JSON.stringify({
                      event_id: eventId,
                      wallets: [selectedAttendeeWallet],
                      tx_hash: receipt.transactionHash,
                    })
                  });

                  // 2. Update local attendees state so dropdown marks them as minted
                  setAttendees(prev => prev.map(a =>
                    a.wallet_address === selectedAttendeeWallet
                      ? { ...a, is_certificate_sent: true }
                      : a
                  ));

                  // 3. Send congratulatory email to the attendee
                  const emailPayload = {
                    attendeeName:  selectedAttendee?.full_name ?? "Attendee",
                    attendeeEmail: selectedAttendee?.email ?? "",
                    eventName:     getEventTitle(),
                    txHash:        receipt.transactionHash,
                  };
                  console.log("[CERT EMAIL] Payload being sent:", emailPayload);

                  const emailRes = await fetch("/api/send-certificate-email", {
                    method: "POST",
                    headers: { "Content-Type": "application/json" },
                    body: JSON.stringify(emailPayload),
                  });

                  const emailData = await emailRes.json().catch(() => ({}));

                  if (emailRes.ok && emailData.success) {
                    toast.success(`🎓 Certificate Minted & Email Sent!`, {
                      description: `${selectedAttendee?.full_name} has been notified at ${selectedAttendee?.email}.`,
                    });
                  } else {
                    // Minting succeeded even if email fails — still report success
                    const errMsg = emailData?.error ?? `HTTP ${emailRes.status}`;
                    console.error("[CERT EMAIL] Failed:", errMsg);
                    toast.success(`Certificate Minted for ${selectedAttendee?.full_name}!`);
                    toast.warning(`Email failed: ${errMsg}`);
                  }

                  // 4. Clear form
                  setSelectedAttendeeWallet("");
                  setCertFile(null);

                } catch (err) {
                  toast.error("Database sync failed, but certificate was minted on-chain.");
                }
              }}
              onError={(err) => {
                setIsUploading(false);
                toast.error("Transaction failed", { description: err.message });
              }}
              className="!w-full !bg-gradient-to-r !from-purple-600 !to-blue-600 hover:!from-purple-500 hover:!to-blue-500 !text-white !font-bold !text-lg !rounded-xl !h-14 !transition-all"
            >
              {isUploading ? (
                 <span className="flex items-center gap-2 justify-center">
                   <Loader2 className="w-5 h-5 animate-spin" /> Uploading to IPFS...
                 </span>
              ) : !selectedAttendeeWallet ? (
                 "Select an Attendee"
              ) : !certFile ? (
                 "Upload Certificate Image"
              ) : (
                 `Mint to ${selectedAttendee?.full_name}`
              )}
            </TransactionButton>
          )}
        </div>
      </div>
    </div>
  );
}

